@startuml
object "Service" as databaseService

object "InputPort" as databaseInputPort
databaseInputPort : location: l
databaseInputPort : protocol: p

object Module

databaseService *-- databaseInputPort
Module *-- databaseService


note left of databaseInputPort::"protocol: p"
  Update the allias
  In the protocol spec
  Full model design TBD
end note

@enduml

